version:  "3.8"
services:
  mysql_db_container:
    image: mysql:5.7.32
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8181:8080

  analytics:
    #image: 'analytics:latest'
    build:
      context: ../noc/projects/analytics/
      dockerfile: Dockerfile
    restart: on-failure
    container_name: analytics
    ports:
      - '8090:8080'
    networks:
      - analytics

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/conf
      - ./prometheus/data:/etc/prometheus/data
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=200h
      - --web.enable-admin-api
      - --web.enable-lifecycle

    restart: always
    ports:
      - 9090:9090
    networks:
      - prometheus



  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/

    networks:
      - alertmanager
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      #- '--store.path=/etc/alertmanager'

      #      node-exporter:
      #       image: prom/node-exporter:latest
      #      container_name: node
      #     restart: always
      #    volumes:
      #     - /proc:/host/proc:ro
      #    - /sys:/host/sys:ro
      #   - /:/rootfs:ro
      #command:
      # - '--path.procfs=/host/proc'
      #- '--path.rootfs=/rootfs'
      #- '--path.sysfs=/host/sys'
      #- '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    # ports:
    #  - 9100:9100


networks:
  mysql:
    driver: bridge

  analytics:
    driver: bridge

  prometheus:
    driver: bridge

  grafana:
    driver: bridge

  alertmanager:
    driver: bridge

  adminer:
    driver: bridge

volumes:
  mysql_db_data_container:
